# Generated by Django 2.0.4 on 2018-04-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.CharField(max_length=30)),
                ('productName', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=12)),
                ('productFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
