# Generated by Django 2.0.4 on 2018-04-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printerCtrl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('productID',)},
        ),
    ]
